version: '3'

services:
  apache:
    build:
      context: .
      dockerfile: ./docker/apache/apache.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/nginx.dockerfile
    ports:
      - "2121:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - apache

  php:
    build:
      context: .
      dockerfile: ./docker/app/app.dockerfile
    volumes:
      - ./src:/var/www/html